payouts_csv: 'test.csv'
msig_alias_json: 'msigs.json' 
refund_destination: wd
keys: 'keys.json'
refund_lock_duration_in_seconds: 10000 # 1 hour
contract_info: 'deploy.json'
fee_wallet: '0:7521327f18e2696a4a97d556361d0e5025472a00d9c4d3573508f508f2bff152'
fee_wallet_keys: '/Users/ivan/surf.keys.json'
msig_abi: './contracts/multisig.abi.json'